version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: edulink-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: edulink
    ports:
      - "5432:5432"
    volumes:
      - edulink-db-data:/var/lib/postgresql/data

volumes:
  edulink-db-data:
